version: '3'
services:
  postgres:
    image: postgres:10
    environment:
      POSTGRES_PASSWORD: "banco"
      POSTGRES_DATABASE: ufu
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    restart: always

  web:
    build: .
    ports:
        - "5000:5000"
    container_name: asa
    depends_on: 
        - postgres
    environment:
      - DBUSER=postgres
      - DBPASS="banco"
      - DBHOST=postgres        
      - DBNAME=ufu